[project]
name = "groqmate"
version = "0.0.1[project]
name = "groqmate"
version = "0.1.0"
dependencies = [
    "groq",
    "python-dotenv",
    "pydantic"  
]

[project.optional-dependencies]
cli = [
    "textual>=0.70.0"
]

